server:
  port: 5555

spring:
  redis:
    host: 39.106.76.206
    port: 6379
    password: 123456
    database: 1
    pool:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms  #需要注意下这里的写法
        max-idle: 500
